### ISSUE TITLE
Connection disconnection during download

### ISSUE THREAD

**Issue by Endless1ve** [project-fika/Fika-Server#13]
If the host's card loads for more than 2:30 minutes, then the host is disabled and the raid disappears from the other player. Only re-entry helps.

"COOP SESSION HAS BEEN ENDED: ping-timeout"

![image](https://github.com/project-fika/Fika-Server/assets/64796904/05adac61-b1b5-41ce-831c-a14959ab9246)

**Comment by Lacyway** [comment]
This has been fixed in 2.0.1, latest release for 3.8.1.
