### ISSUE TITLE
Pop up

### ISSUE THREAD

**Issue by SevenBeloved** [project-fika/Fika-Server#15]
The 30 second pop up window to accept your terms of service with only an exit option that exits the game is stupid. Add an accept button because thats annoying, stupid, and only some shit a big Corpo would do like EA or Sony. Ill accept it but don't force me to sit and stare at a message I read in 10 seconds.

**Comment by Lacyway** [comment]
I would have taken this seriously until you made 2 issues for the same thing in frustration.
Have you considered that there is no other way for us to do it as of now? If you wait 30 seconds, you can click "Ok" next time. It's only the first.

**Comment by SevenBeloved** [comment]
I put the issue on two different things because I dont know which one you have it in so I wanted to make sure it was known. Have I considered that there is no way for you to do it, yes, but I have also considered that it shouldnt be that hard either and should be possible.

**Comment by Lacyway** [comment]
> I put the issue on two different things because I dont know which one you have it in so I wanted to make sure it was known. Have I considered that there is no way for you to do it, yes, but I have also considered that it shouldnt be that hard either and should be possible.

Feel free to PR the change and we'll merge then :)

**Comment by ChristianMHolt** [comment]
> The 30 second pop up window to accept your terms of service with only an exit option that exits the game is stupid. Add an accept button because thats annoying, stupid, and only some shit a big Corpo would do like EA or Sony. Ill accept it but don't force me to sit and stare at a message I read in 10 seconds.

Chill bro. Having to wait 30 seconds is hardly even an inconvenience considering you didn't have to donate the probably hundreds of hours it took to develop this in the first place.
