### ISSUE TITLE
[INSURANCE BRANCH] Hotkeys are reset on extract (0-9)

### ISSUE THREAD

**Issue by Lacyway** [project-fika/Fika-Server#52]

**Comment by nexus4880** [comment]
Could not replicate.

**Comment by Lacyway** [comment]
Were you on the insurance branch? I just tested on `main`, it works. Then rebuilt on `insurance-changes` and lost my quick binds on exfil.

**Comment by Lacyway** [comment]
Interestingly enough, they stay on the profile but are not visible. Confirmed on ~5 people who were playing.
```json
"fastPanel": {
	"Item4": "46b97da00ca41ab76268d3d0",
	"Item5": "d7442181c9306a9f77a18903"
},
```

**Comment by ArchangelWTF** [comment]
Feature has now been moved into the 3.10 dev branch as it's stable enough, will do and await further tests there.
