### ISSUE TITLE
Dedicated game server

### ISSUE THREAD

**Issue by hellchickens** [project-fika/Fika-Server#55]
I wish there is feature to avoid running actual game server on local machine inside the game client. Will be good if there is ability to run game server on the host with data server (spt server bin I mean) external to any actual game client.
Or at least add ability to launch game host without actual player on it, e.g. spectator. 

The main point here is to move any game logic calc from actual players.

**Comment by Lacyway** [comment]
There's an active discussion regarding this on our discord. Dedicated clients will hopefully come soon.
