### ISSUE TITLE
[BUG/3.10] Host data is never saved

### ISSUE THREAD

**Issue by Lacyway** [project-fika/Fika-Server#77]
Reverting to pre-insurance fixes the issue, need to investigate the saving somewhere in the Insurance controller most likely.

**Comment by ArchangelWTF** [comment]
With commits https://github.com/project-fika/Fika-Server/commit/b04c4f7410a067cee79baffc84433fb32419b3d5 & https://github.com/project-fika/Fika-Server/commit/bc3d36743be51c7e4342cc390a8a85325983c557 as well as https://github.com/project-fika/Fika-Plugin/commit/1af07f7a1c58220d3d424acbc25ee468f5b2953a on the client this seems to be fixed, closing for now.
