### ISSUE TITLE
Client/Server mod comparison not checking for empty values

### ISSUE THREAD

**Issue by ItsDyze** [project-fika/Fika-Server#81]
Probably better if handled in the "Game Panel" my hoster provides. But I guess I wasn't the only one checking for why my client mdos wasn't matching the server's.

The comparison between client and server's required mods is returning a mismatch when the server is configured to have a required mod set as an empty string

https://github.com/project-fika/Fika-Server/blob/82ed9ea3072d087344a95190baab4798c4c25a9c/src/controllers/FikaClientController.ts#L28

A screenshot of me struggling with the game panel:
![image](https://github.com/user-attachments/assets/141b9cac-dc9a-47d6-ac4d-0e3e6ba113e6)

**Comment by Lacyway** [comment]
What host are you using? We do not support hosting services as they violate our license.

**Comment by ItsDyze** [comment]
I guess TOS are fine as the hoster (hostinger) only advertises a VPS with a panel (CubeCoders AMP) on top for ease of dedicated game server installation.
If you plan on getting them to back off, let me know I’ll set it up manually :-)

Although for the input checking in the code, I can also send in a PR if you’d like.

**Comment by Lacyway** [comment]
Sure, send in a PR and I'll take a look.

**Comment by ItsDyze** [comment]
#82 - Hope it's alright with your coding standards
