### ISSUE TITLE
Trying to access the GameWorld when not in raid

### ISSUE THREAD

**Issue by PiCKaChOK** [project-fika/Fika-Server#96]
Hi, yesterday I ran into a problem when playing with a friend, when entering a raid my friend has a table popping up with the message “Error: trying to access the GameWorld when not in raid”.

Mod me and my friend used for the first time, specifically the problem of what part of the mod - server or client do not know, the solution is also not found. The mod was configured according to the guide, under radmin vpn.

In the raid loads, but the sign hangs in the middle of the screen, any of its closure throws my friend out of the raid, forcing him to face an endless bagel at the bottom right, and glitches picture (disappears body chvk, but remains unloaded, armor, helmet, weapons, sometimes can twitch the picture), like you can go through esc in the main menu if the error window was closed, move with this error sign on the map can be, to look at how your teammate runs, but no more.

If this is some kind of bug, or our crooked hands, please help.
More information on hand do not possess, for logs or clarification I need to contact a friend (for inaccuracies in the translation blame Deepl Translate ru>eng)

spt 3.10.2
mod list:
fika-server
Fika.Release. 1.0.3.0
VCQL-2.O.3
MoreCheckmarks-1.5.15-for-3.10.0-33420
SkillsExtended
AmandsSense.2.0.0
acidphantasm-bosseshavelegamedals
acidphantasm-refsptfriendlyquests
Increase Climb Height 1.3
kmyuhkyuk-GamePanelHUD.Release_3.2.0
kmyuhkyuk-EFTApi.Release_1.3.0
Gaylatea-UseLooseLoot- 1.3.0
Customlnteractions- 1.6.0
UnityToolkit-1.0.1
Declutterer.
Tyfon-UlFixes-3.0.1
DrakiaXYZ-BigBrain- 1.2
SAIN-3.2.O-Release
DrakiaXYZ-Waypoints- 1.6.0
AmandsGraphics. 1.6.5
DynamicMaps-0.5.2

**Comment by Lacyway** [comment]
We don't provide support here - use our discord.
In this case it's `SkillsExtended`, remove it.
