### ISSUE TITLE
All Items get 'Found In Raid' marker after transit

### ISSUE THREAD

**Issue by xiaoxufeiji1a** [project-fika/Fika-Server#97]
All Items what player carrying will get 'Found In Raid' marker,after player use transit extraction to other map.
Bring any non-'FIR' item then transit will make items 'FIR',make items easy turn to 'FIR'.
This could be a game changer because of many quests need 'FIR' item to complete.

I have not seen this bug in original SPTarkov,so I guess it's a Fika bug.

**Comment by Lacyway** [comment]
Please use our Discord for bug reports
